dist: trusty
jobs:
  include:
    - stage: testing the build
      script:
        - if  [ -z "$TRAVIS_TAG" ]; then DOCKER_TAG=sha-`echo "$TRAVIS_COMMIT" | cut -c1-7`;  else DOCKER_TAG=$TRAVIS_TAG; fi
        - echo "Docker tag would be $DOCKER_TAG"
        - docker build -t invanalabs/invana-studio .
    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t invanalabs/invana-studio .
        - if  [ -z "$TRAVIS_TAG" ]; then DOCKER_TAG=sha-`echo "$TRAVIS_COMMIT" | cut -c1-7`;  else DOCKER_TAG=$TRAVIS_TAG; fi
        - docker tag invanalabs/invana-studio invanalabs/invana-studio:"$DOCKER_TAG"
        - docker tag invanalabs/invana-studio invanalabs/invana-studio:latest
        - docker push invanalabs/invana-studio:"$DOCKER_TAG"
        - docker push invanalabs/invana-studio:latest
    - stage: deploy to heroku edge version
      script: skip
      deploy: &heroku
        provider: heroku
        app: invana-studio-edge
        api_key: $HEROKU_AUTH_TOKEN
        on:
          all_branches: true
    - stage: deploy to heroku
      script: skip
      deploy: &heroku
        provider: heroku
        app: invana-studio
        api_key: $HEROKU_AUTH_TOKEN
        on:
          tags: true
          all_branches: true
    - stage: test edge deployemnt
      script: 'curl http://invana-studio-edge.herokuapp.com'
    - stage: test prod deployemnt
      script: 'curl http://invana-studio.herokuapp.com'

stages:
  - name: deploy to heroku edge version
    if: branch = develop AND type != pull_request
  - name: test edge depl
    if: branch = develop AND type != pull_request
  - name: deploy to heroku
    if: tag IS present AND type != pull_request
  - name: test prod deployemnt
    if: tag IS present AND type != pull_request
  - name: build and push docker image
    if: tag IS present AND type != pull_request
