name: Deploy to Heroku

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: akhileshns/heroku-deploy@master # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "graph-explorer"
          heroku_email: "rrmerugu@gmail.com"
          buildpack: ""
