name: Docker Build Push

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: invanalabs/graph-explorer
          tag_with_ref: true
          tag_with_sha: true
