name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for being awesome and taking part in our design, development and feedback loop. Cheers.'
        pr-message: 'Thank you for being awesome and bringing your skills to this project; This PR shall be reviewed soon.'
